name: Показать время

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  show-current-time:
    runs-on: ubuntu-latest
    steps:
      - name: вывести дату и время
        run: date
